WITH CTE AS
(
	SELECT
		CASE
			WHEN MONTH(DATE) IN(11, 12, 1) THEN 'HIGH_RISK'
			ELSE 'NON_HIGH_RISK'
		END	AS BUCKET,
		IS_FRAUD
	FROM
		joined_tables_for_analysis
)
SELECT
	BUCKET,
	SUM(IS_FRAUD)	AS IS_FRAUD_QUANTITY,
	COUNT(*)		AS TRANSACTION_QUANTITY
FROM
	CTE
WHERE
	BUCKET IN('HIGH_RISK')
GROUP BY
	BUCKET;