WITH CTE AS
(
	SELECT
		CASE
			WHEN CAST(JTA.TIME AS varchar) BETWEEN '12:00:00' AND '17:00:00' AND MONTH(DATE) IN(1, 11, 12) THEN 'HIGH_RISK'
			ELSE 'NON_HIGH_RISK'
		END	AS BUCKET,
		IS_FRAUD
	FROM
		joined_tables_for_analysis	AS JTA
)
SELECT
	BUCKET,
	SUM(IS_FRAUD)	AS IS_FRAUD_QUANTITY,
	COUNT(*)		AS TRANSACTION_QUANTITY
FROM
	CTE
WHERE
	BUCKET IN('HIGH_RISK')
GROUP BY
	BUCKET;