WITH CTE AS
(
	SELECT
		TRIM(ID)																				AS ID,
		TRIM(CUSTOMER_ID)																		AS CUSTOMER_ID,
		CASE UPPER(TRIM(TYPE))
			WHEN 'CH' THEN 'CHECKING'
			WHEN 'S' THEN 'SAVINGS'
			WHEN 'W' THEN 'WALLET'
			WHEN 'VW' THEN 'VIRTUAL WALLET'
			WHEN 'CR' THEN 'CREDIT'
			ELSE REPLACE(UPPER(TRIM(TYPE)), '_', ' ')
		END																						AS TYPE,
		CASE
			WHEN UPPER(CURRENCY) LIKE '%US%' OR UPPER(CURRENCY) LIKE '%USD%' OR UPPER(CURRENCY) LIKE '%US_DOLLAR%' THEN 'USD'
			WHEN UPPER(CURRENCY) LIKE '%EUR%' THEN 'EUR'
			WHEN UPPER(CURRENCY) LIKE '%GBP%' OR UPPER(CURRENCY) LIKE '%POUND%' THEN 'GBP'
			WHEN CURRENCY LIKE '%$R%' OR UPPER(CURRENCY) LIKE '%BRL%' OR UPPER(LTRIM(RTRIM(CURRENCY))) = 'REAL' THEN 'BRL'
			WHEN UPPER(CURRENCY) LIKE '%MXN%' OR UPPER(CURRENCY) LIKE '%MEX%' THEN 'MXN'
			ELSE CURRENCY
		END																						AS CURRENCY,
		TRIM(REPLACE(REPLACE(REPLACE(REPLACE(BALANCE, '"', ''), '$', ''), '''', ''),',', ''))	AS BALANCE,
		TRIM(REPLACE(OPEN_DATE, '"', ''))														AS OPEN_DATE,
		CASE UPPER(TRIM(STATUS))
			WHEN 'A' THEN 'ACTIVE'
			WHEN 'I' THEN 'INACTIVE'
			WHEN 'B' THEN 'BLOCKED'
			ELSE UPPER(TRIM(STATUS))
		END																						AS STATUS,
		CONCAT(ID, CUSTOMER_ID, CURRENCY, BALANCE, OPEN_DATE, STATUS)							AS CONCATENATION
	FROM
		'project/UNCLEAN_DATASETS/accounts.csv'
)
SELECT
	ID,
	CUSTOMER_ID,
	TYPE,
	CURRENCY,
	BALANCE,
	CASE
		WHEN OPEN_DATE LIKE '%/%' THEN CONCAT(RIGHT(OPEN_DATE, 4), '-', LEFT(OPEN_DATE, 2), '-', SUBSTRING(OPEN_DATE, 4, 2))
		WHEN SUBSTRING(OPEN_DATE, 3, 1) = '-' THEN CONCAT(RIGHT(OPEN_DATE, 4), '-', SUBSTRING(OPEN_DATE, 4, 2), '-', LEFT(OPEN_DATE, 2))
		ELSE OPEN_DATE
	END	AS OPEN_DATE,
	STATUS
FROM
	CTE
WHERE
	UPPER(CONCATENATION) NOT LIKE '%(BLANK)%'
	AND CONCATENATION NOT LIKE '%NULL%'
	AND REPLACE(CONCATENATION, ' ', '') <> ''