WITH CTE AS
(
	SELECT
		ID																	AS ID,
		REPLACE(REPLACE(FIRST_NAME, '''', ''), '"', '')						AS FIRST_NAME,
		REPLACE(REPLACE(LAST_NAME, '''', ''), '"', '')						AS LAST_NAME,
		AGE																	AS AGE,
		GENDER																AS GENDER,
		CASE
			WHEN LEN(COUNTRY) = 2 THEN UPPER(DETECT_COUNTRY(COUNTRY))
			ELSE UPPER(COUNTRY)
		END																	AS COUNTRY,
		REPLACE(REPLACE(REPLACE(CREDIT_LIMIT, ',', ''), '$', ''), ' ', '')	AS CREDIT_LIMIT,
		REPLACE(REPLACE(CUSTOMER_LIFETIME_VALUE, ',', ''), '''', '')		AS CUSTOMER_LIFETIME_VALUE
	FROM
		'project/UNCLEAN_DATASETS/customers.csv'
)
SELECT
	ID,
	CONCAT(FIRST_NAME, ' ', LAST_NAME)	AS FULL_NAME,
	AGE,
	CASE
		WHEN GENDER IS NULL AND FIRST_NAME IN ('Sem', 'Matheus') THEN 'MALE'
		WHEN GENDER IS NULL THEN UPPER(REPLACE(GUESS_GENDER(FIRST_NAME), 'mostly_', ''))
		ELSE UPPER(GENDER)
	END									AS GENDER,
	COUNTRY,
	CREDIT_LIMIT,
	CUSTOMER_LIFETIME_VALUE
FROM
	CTE