WITH COMBINED_FOREX_PAIRS_CTE AS
(
	SELECT
		DATE,
		FX_PAIR,
		LEFT(FX_PAIR, 3)	AS PRINCIPAL_CURRENCY,
		RIGHT(FX_PAIR, 3)	AS SECONDARY_CURRENCY,
		OPEN_PRICE
	FROM
		(
			UNPIVOT 'project/CLEAN_DATASETS/CLEAN_COMBINED_EXCHANGE_RATES.csv'
			ON COLUMNS(* EXCLUDE DATE) INTO NAME FX_PAIR VALUE OPEN_PRICE
		)
),
CTE AS
(
	SELECT
		FC.TRANSACTION_ID										AS TRANSACTION_ID,
		GET_ML_RESULT(T.IS_FRAUD::BOOLEAN, FD.FLAGGED::BOOLEAN)	AS ML_RESULT,
		INVESTIGATION_COST,
		CUSTOMER_SUPPORT_COST,
		LOST_INTERCHANGE
	FROM
		'project/UNCLEAN_DATASETS/fraud_costs.csv'				FC
		INNER JOIN 'project/CLEAN_DATASETS/TRANSACTIONS.csv'	T ON FC.TRANSACTION_ID = T.ID
		INNER JOIN 'project/CLEAN_DATASETS/FRAUD_DECISIONS.csv'	FD ON T.ID = FD.TRANSACTION_ID
),
ACCOUNT_CHARGED_AMOUNT_CTE AS
(
	SELECT
		T.ID	AS TRANSACTION_ID,
		A.CURRENCY,
		T.DATE,
		CASE
			WHEN A.CURRENCY = CURRENCY_PAIR_CTE.PRINCIPAL_CURRENCY THEN T.AMOUNT / CURRENCY_PAIR_CTE.OPEN_PRICE
			WHEN A.CURRENCY = CURRENCY_PAIR_CTE.SECONDARY_CURRENCY THEN T.AMOUNT * CURRENCY_PAIR_CTE.OPEN_PRICE
			ELSE T.AMOUNT
		END		AS ACCOUNT_CHARGED_AMOUNT
	FROM
		'project/CLEAN_DATASETS/TRANSACTIONS.csv'			T
		INNER JOIN 'project/CLEAN_DATASETS/ACCOUNTS.csv'	A ON T.ACCOUNT_ID = A.ID
		LEFT JOIN COMBINED_FOREX_PAIRS_CTE					CURRENCY_PAIR_CTE ON CURRENCY_PAIR_CTE.DATE = T.DATE AND
			(
				(CURRENCY_PAIR_CTE.PRINCIPAL_CURRENCY = A.CURRENCY AND CURRENCY_PAIR_CTE.SECONDARY_CURRENCY = T.CURRENCY)
				OR (CURRENCY_PAIR_CTE.PRINCIPAL_CURRENCY = T.CURRENCY AND CURRENCY_PAIR_CTE.SECONDARY_CURRENCY = A.CURRENCY)
			)
),
USD_FEES_CTE AS
(
	SELECT
		ACA_CTE.TRANSACTION_ID,
		CASE
			WHEN USD_PAIR_CTE.PRINCIPAL_CURRENCY = 'USD' THEN ACCOUNT_CHARGED_AMOUNT / USD_PAIR_CTE.OPEN_PRICE
			WHEN USD_PAIR_CTE.SECONDARY_CURRENCY = 'USD' THEN ACCOUNT_CHARGED_AMOUNT * USD_PAIR_CTE.OPEN_PRICE
			ELSE ACCOUNT_CHARGED_AMOUNT
		END	AS TRANSACTION_USD_AMOUNT
	FROM
		ACCOUNT_CHARGED_AMOUNT_CTE			ACA_CTE
		LEFT JOIN COMBINED_FOREX_PAIRS_CTE	USD_PAIR_CTE ON ACA_CTE.DATE = USD_PAIR_CTE.DATE AND
		(
			(USD_PAIR_CTE.PRINCIPAL_CURRENCY = ACA_CTE.CURRENCY AND USD_PAIR_CTE.SECONDARY_CURRENCY = 'USD')
			OR (USD_PAIR_CTE.PRINCIPAL_CURRENCY = 'USD' AND USD_PAIR_CTE.SECONDARY_CURRENCY = ACA_CTE.CURRENCY)
		)
)
SELECT
	CTE.TRANSACTION_ID,
	CASE
		WHEN ML_RESULT = 'FALSE NEGATIVE' THEN -USD_FEES_CTE.TRANSACTION_USD_AMOUNT
		ELSE 0
	END	AS FRAUD_LOSS,
	CASE
		WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
		ELSE -INVESTIGATION_COST
	END	AS INVESTIGATION_COST,
	CASE
		WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
		ELSE -CUSTOMER_SUPPORT_COST
	END	AS CUSTOMER_SUPPORT_COST,
	CASE
		WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
		ELSE -LOST_INTERCHANGE
	END	AS LOST_INTERCHANGE
FROM
	CTE
	INNER JOIN ACCOUNT_CHARGED_AMOUNT_CTE	ACA_CTE ON CTE.TRANSACTION_ID = ACA_CTE.TRANSACTION_ID
	INNER JOIN USD_FEES_CTE ON ACA_CTE.TRANSACTION_ID = USD_FEES_CTE.TRANSACTION_ID