WITH CTE AS
(
	SELECT
		FC.TRANSACTION_ID										AS TRANSACTION_ID,
		GET_ML_RESULT(T.IS_FRAUD::BOOLEAN, FD.FLAGGED::BOOLEAN)	AS ML_RESULT,
		INVESTIGATION_COST,
		CUSTOMER_SUPPORT_COST,
		LOST_INTERCHANGE
	FROM
		'project/UNCLEAN_DATASETS/fraud_costs.csv'				FC
		INNER JOIN 'project/CLEAN_DATASETS/TRANSACTIONS.csv'	T ON FC.TRANSACTION_ID = T.ID
		INNER JOIN 'project/CLEAN_DATASETS/FRAUD_DECISIONS.csv'	FD ON T.ID = FD.TRANSACTION_ID
)
SELECT
	TRANSACTION_ID,
	CASE
		WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
		ELSE -INVESTIGATION_COST
	END	AS INVESTIGATION_COST,
	CASE
		WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
		ELSE -CUSTOMER_SUPPORT_COST
	END	AS CUSTOMER_SUPPORT_COST,
	CASE
		WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
		ELSE -LOST_INTERCHANGE
	END	AS LOST_INTERCHANGE
FROM
	CTE