SELECT
	BRLMXN.Price	AS DATE,
	BRLMXN.Open		AS BRLMXN,
	EURBRL.Open		AS EURBRL,
	EURMXN.Open		AS EURMXN,
	EURUSD.Open		AS EURUSD,
	GBPBRL.Open		AS GBPBRL,
	GBPEUR.Open		AS GBPEUR,
	GBPMXN.Open		AS GBPMXN,
	GBPUSD.Open		AS GBPUSD,
	USDBRL.Open		AS USDBRL,
	USDMXN.Open		AS USDMXN,
FROM
	'project/UNCLEAN_DATASETS/UNCLEAN_CURRENCY_EXCHANGE_RATES/BRLMXN_RATES.csv'				BRLMXN
	INNER JOIN 'project/UNCLEAN_DATASETS/UNCLEAN_CURRENCY_EXCHANGE_RATES/EURBRL_RATES.csv'	EURBRL ON EURBRL.Price = BRLMXN.Price
	INNER JOIN 'project/UNCLEAN_DATASETS/UNCLEAN_CURRENCY_EXCHANGE_RATES/EURMXN_RATES.csv'	EURMXN ON EURMXN.Price = BRLMXN.Price
	INNER JOIN 'project/UNCLEAN_DATASETS/UNCLEAN_CURRENCY_EXCHANGE_RATES/EURUSD_RATES.csv'	EURUSD ON EURUSD.Price = BRLMXN.Price
	INNER JOIN 'project/UNCLEAN_DATASETS/UNCLEAN_CURRENCY_EXCHANGE_RATES/GBPBRL_RATES.csv'	GBPBRL ON GBPBRL.Price = BRLMXN.Price
	INNER JOIN 'project/UNCLEAN_DATASETS/UNCLEAN_CURRENCY_EXCHANGE_RATES/GBPEUR_RATES.csv'	GBPEUR ON GBPEUR.Price = BRLMXN.Price
	INNER JOIN 'project/UNCLEAN_DATASETS/UNCLEAN_CURRENCY_EXCHANGE_RATES/GBPMXN_RATES.csv'	GBPMXN ON GBPMXN.Price = BRLMXN.Price
	INNER JOIN 'project/UNCLEAN_DATASETS/UNCLEAN_CURRENCY_EXCHANGE_RATES/GBPUSD_RATES.csv'	GBPUSD ON GBPUSD.Price = BRLMXN.Price
	INNER JOIN 'project/UNCLEAN_DATASETS/UNCLEAN_CURRENCY_EXCHANGE_RATES/USDBRL_RATES.csv'	USDBRL ON USDBRL.Price = BRLMXN.Price
	INNER JOIN 'project/UNCLEAN_DATASETS/UNCLEAN_CURRENCY_EXCHANGE_RATES/USDMXN_RATES.csv'	USDMXN ON USDMXN.Price = BRLMXN.Price
WHERE
	BRLMXN.Price <> 'Ticker'