WITH CTE AS
(
	SELECT
		CASE
			WHEN CREDIT_LIMIT < 1000 THEN 'STARTER'
			WHEN CREDIT_LIMIT >= 1000 AND BALANCE < 5000 THEN 'STANDARD'
			WHEN CREDIT_LIMIT >= 5000 AND BALANCE < 15000 THEN 'MID_TIER'
			WHEN CREDIT_LIMIT >= 15000 AND BALANCE < 30000 THEN 'PREMIUM'
			WHEN CREDIT_LIMIT >= 30000 THEN 'VIP'
		END	AS BUCKET,
		IS_FRAUD
	FROM
		joined_tables_for_analysis
)
SELECT
	BUCKET,
	SUM(IS_FRAUD)	AS IS_FRAUD_QUANTITY,
	COUNT(*)		AS TRANSACTION_QUANTITY
FROM
	CTE
GROUP BY
	BUCKET;