SELECT
	ID,
	CASE
		WHEN CUSTOMER_LIFETIME_VALUE < 10000 THEN 'LOW_VALUE'
		WHEN CUSTOMER_LIFETIME_VALUE >= 1000 AND BALANCE < 10000 THEN 'MID_VALUE'
		WHEN CUSTOMER_LIFETIME_VALUE >= 10000 AND BALANCE < 100000 THEN 'HIGH_VALUE'
		WHEN CUSTOMER_LIFETIME_VALUE >= 100000 THEN 'VIP'
	END	AS BUCKET
FROM
	data_source_to_analyze_iv