WITH CTE AS
(
	SELECT
		CASE
			WHEN CUSTOMER_LIFETIME_VALUE < 10000 THEN 'LOW_VALUE'
			WHEN CUSTOMER_LIFETIME_VALUE >= 1000 AND BALANCE < 10000 THEN 'MID_VALUE'
			WHEN CUSTOMER_LIFETIME_VALUE >= 10000 AND BALANCE < 100000 THEN 'HIGH_VALUE'
			WHEN CUSTOMER_LIFETIME_VALUE >= 100000 THEN 'VIP'
		END	AS BUCKET,
		IS_FRAUD
	FROM
		joined_tables_for_analysis
)
SELECT
	BUCKET,
	SUM(IS_FRAUD)	AS IS_FRAUD_QUANTITY,
	COUNT(*)		AS TRANSACTION_QUANTITY
FROM
	CTE
GROUP BY
	BUCKET;