SELECT
	EXTRACT('hour' FROM TIME::TIME)	AS HOUR,
	SUM(IS_FRAUD)					AS IS_FRAUD_QUANTITY,
	COUNT(*)						AS TRANSACTION_QUANTITY
FROM
	joined_tables_for_analysis
GROUP BY
	EXTRACT('hour' FROM TIME::TIME);