SELECT
	DT.COUNTRY	AS 'TRAN_COUNTRY',
	C.COUNTRY	AS 'CUS_COUNTRY',
	DT.COUNTRY = C.COUNTRY	AS 'IS_SAME'
FROM
	'project/ANALYSIS/DENORMALIZED_TRANSACTIONS.csv'	DT
	INNER JOIN 'project/CLEAN_DATASETS/ACCOUNTS.csv'	A ON DT.ACCOUNT_ID = A.ID
	INNER JOIN 'project/CLEAN_DATASETS/CUSTOMERS.csv'	C ON A.CUSTOMER_ID = C.ID