WITH CTE AS
(
	SELECT
		ID,
		CASE
			WHEN CURRENCY = 'USD' THEN 1
			WHEN CURRENCY = 'BRL' THEN 4.99
			WHEN CURRENCY = 'EUR' THEN 0.85
			WHEN CURRENCY = 'GBP' THEN 0.74
			WHEN CURRENCY = 'MXN' THEN 17.18
		END	AS RATE
	FROM
		'project/CLEAN_DATASETS/TRANSACTIONS.csv'	T
	WHERE
		IS_FRAUD = 0
)
SELECT
	T.ID,
	T.CURRENCY,
	T.AMOUNT,
	CTE.RATE,
	T.AMOUNT / CTE.RATE	AS USD_AMOUNT
FROM
	'project/CLEAN_DATASETS/TRANSACTIONS.csv'	T
	INNER JOIN CTE ON T.ID = CTE.ID
WHERE
	T.IS_FRAUD = 0