SELECT
	MONTH(DATE)				AS MONTH,
	TRANSACTION_COUNTRY,
	SUM(IS_FRAUD)			AS IS_FRAUD_QUANTITY,
	COUNT(*)				AS TRANSACTION_QUANTITY
FROM
	joined_tables_for_analysis
GROUP BY
	MONTH(DATE),
	TRANSACTION_COUNTRY;