WITH COMBINED_FOREX_PAIRS_CTE AS
(
	SELECT
		DATE,
		FX_PAIR,
		LEFT(FX_PAIR, 3)	AS PRINCIPAL_CURRENCY,
		RIGHT(FX_PAIR, 3)	AS SECONDARY_CURRENCY,
		OPEN_PRICE
	FROM
		(
			UNPIVOT 'project/CLEAN_DATASETS/CLEAN_COMBINED_EXCHANGE_RATES.csv'
			ON COLUMNS(* EXCLUDE DATE) INTO NAME FX_PAIR VALUE OPEN_PRICE
		)
),
AGG_FX_RATES_CTE AS
(
	SELECT
		T.ID			AS ID,
		T.DATE			AS DATE,
		T.ACCOUNT_FEES	AS ACCOUNT_FEES,
		A.CURRENCY		AS ACC_CURR,
		CASE
			WHEN A.CURRENCY = CFP_CTE.PRINCIPAL_CURRENCY THEN T.AMOUNT / CFP_CTE.OPEN_PRICE
			WHEN A.CURRENCY = CFP_CTE.SECONDARY_CURRENCY THEN T.AMOUNT * CFP_CTE.OPEN_PRICE
			ELSE T.AMOUNT
		END				AS ACCOUNT_CHARGED_AMOUNT
	FROM
		'project/CLEAN_DATASETS/TRANSACTIONS.csv'		AS T
		LEFT JOIN 'project/CLEAN_DATASETS/ACCOUNTS.csv'	AS A ON A.ID = T.ACCOUNT_ID
		LEFT JOIN COMBINED_FOREX_PAIRS_CTE				AS CFP_CTE ON CFP_CTE.DATE = T.DATE AND
		(
			(CFP_CTE.PRINCIPAL_CURRENCY = A.CURRENCY AND CFP_CTE.SECONDARY_CURRENCY = T.CURRENCY)
			OR (CFP_CTE.PRINCIPAL_CURRENCY = T.CURRENCY AND CFP_CTE.SECONDARY_CURRENCY = A.CURRENCY)
		)
)
SELECT
	AFR_CTE.ID,
	CASE
		WHEN CFP_CTE.PRINCIPAL_CURRENCY = 'USD' THEN ACCOUNT_FEES / CFP_CTE.OPEN_PRICE
		WHEN CFP_CTE.SECONDARY_CURRENCY = 'USD' THEN ACCOUNT_FEES * CFP_CTE.OPEN_PRICE
		ELSE ACCOUNT_FEES
	END																	AS USD_FEES,
	FD.INVESTIGATION_COST + CUSTOMER_SUPPORT_COST + LOST_INTERCHANGE	AS TOTAL_COSTS
FROM
	AGG_FX_RATES_CTE									AS AFR_CTE
	INNER JOIN 'project/CLEAN_DATASETS/FRAUD_COSTS.csv'	AS FD ON AFR_CTE.ID = FD.TRANSACTION_ID
	LEFT JOIN COMBINED_FOREX_PAIRS_CTE					AS CFP_CTE ON CFP_CTE.DATE = AFR_CTE.DATE AND
	(
		(CFP_CTE.PRINCIPAL_CURRENCY = AFR_CTE.ACC_CURR AND CFP_CTE.SECONDARY_CURRENCY = 'USD')
		OR (CFP_CTE.PRINCIPAL_CURRENCY = 'USD' AND CFP_CTE.SECONDARY_CURRENCY = AFR_CTE.ACC_CURR)
	)