WITH COMBINED_FOREX_PAIRS_CTE AS
(
	SELECT
		DATE,
		FX_PAIR,
		LEFT(FX_PAIR, 3)	AS PRINCIPAL_CURRENCY,
		RIGHT(FX_PAIR, 3)	AS SECONDARY_CURRENCY,
		OPEN_PRICE
	FROM
		(
			UNPIVOT 'project/CLEAN_DATASETS/CLEAN_COMBINED_EXCHANGE_RATES.csv'
			ON COLUMNS(* EXCLUDE DATE) INTO NAME FX_PAIR VALUE OPEN_PRICE
		)
),
AGG_FX_RATES_CTE AS
(
	SELECT
		T.ID					AS ID,
		DATE(T.TIMESTAMP)	AS DATE,
		A.CURRENCY			AS ACC_CURR,
		T.CURRENCY			AS TRAN_CURR,
		T.AMOUNT			AS TRAN_AMOUNT,
		CASE
			WHEN A.CURRENCY = CFP_CTE.PRINCIPAL_CURRENCY THEN T.AMOUNT / CFP_CTE.OPEN_PRICE
			WHEN A.CURRENCY = CFP_CTE.SECONDARY_CURRENCY THEN T.AMOUNT * CFP_CTE.OPEN_PRICE
			ELSE T.AMOUNT
		END					AS ACCOUNT_CHARGED_AMOUNT
	FROM
		'misc/SYNTHETIC_DATASET/transactions.csv'		AS T
		LEFT JOIN 'project/CLEAN_DATASETS/ACCOUNTS.csv'	AS A ON A.ID = T.ACCOUNT_ID
		LEFT JOIN COMBINED_FOREX_PAIRS_CTE				AS CFP_CTE ON CFP_CTE.DATE = DATE(T.TIMESTAMP) AND
		(
			(CFP_CTE.PRINCIPAL_CURRENCY = A.CURRENCY AND CFP_CTE.SECONDARY_CURRENCY = T.CURRENCY)
			OR (CFP_CTE.PRINCIPAL_CURRENCY = T.CURRENCY AND CFP_CTE.SECONDARY_CURRENCY = A.CURRENCY)
		)
)
SELECT
	AFR_CTE.ID,
	AFR_CTE.*,
	CASE
		WHEN CFP_CTE.PRINCIPAL_CURRENCY = 'USD' THEN ACCOUNT_CHARGED_AMOUNT / CFP_CTE.OPEN_PRICE
		WHEN CFP_CTE.SECONDARY_CURRENCY = 'USD' THEN ACCOUNT_CHARGED_AMOUNT * CFP_CTE.OPEN_PRICE
		ELSE ACCOUNT_CHARGED_AMOUNT
	END									AS USD_AMOUNT,
	ACCOUNT_CHARGED_AMOUNT * 0.00185	AS ACCOUNT_FEES,
	CASE
		WHEN CFP_CTE.PRINCIPAL_CURRENCY = 'USD' THEN (ACCOUNT_CHARGED_AMOUNT * 0.00185) / CFP_CTE.OPEN_PRICE
		WHEN CFP_CTE.SECONDARY_CURRENCY = 'USD' THEN (ACCOUNT_CHARGED_AMOUNT * 0.00185) * CFP_CTE.OPEN_PRICE
		ELSE ACCOUNT_CHARGED_AMOUNT * 0.00185
	END									AS USD_FEES
FROM
	AGG_FX_RATES_CTE					AS AFR_CTE
	LEFT JOIN COMBINED_FOREX_PAIRS_CTE	AS CFP_CTE ON CFP_CTE.DATE = AFR_CTE.DATE AND
	(
		(CFP_CTE.PRINCIPAL_CURRENCY = AFR_CTE.ACC_CURR AND CFP_CTE.SECONDARY_CURRENCY = 'USD')
		OR (CFP_CTE.PRINCIPAL_CURRENCY = 'USD' AND CFP_CTE.SECONDARY_CURRENCY = AFR_CTE.ACC_CURR)
	)