WITH CTE AS
(
	SELECT
		FC.TRANSACTION_ID										AS TRANSACTION_ID,
		GET_ML_RESULT(T.IS_FRAUD::BOOLEAN, FD.FLAGGED::BOOLEAN)	AS ML_RESULT,
		TRV.RANDOM_VALUE										AS RANDOM_VALUE
	FROM
		'project/UNCLEAN_DATASETS/fraud_costs.csv'				FC
		INNER JOIN 'project/CLEAN_DATASETS/TRANSACTIONS.csv'	T ON FC.TRANSACTION_ID = T.ID
		INNER JOIN 'project/CLEAN_DATASETS/FRAUD_DECISIONS.csv'	FD ON T.ID = FD.TRANSACTION_ID
		INNER JOIN 'misc/TRANSACTION_RANDOM_VALUES.csv'			TRV ON FC.TRANSACTION_ID = TRV.TRANSACTION_ID
)
SELECT
	TRANSACTION_ID,
	ML_RESULT,
	CASE
		WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
		WHEN ML_RESULT = 'TRUE POSITIVE' THEN ROUND((20 - 5) * RANDOM_VALUE + 5, 2)
		WHEN ML_RESULT = 'FALSE POSITIVE' THEN ROUND((12 - 2) * RANDOM_VALUE + 2, 2)
		WHEN ML_RESULT = 'FALSE NEGATIVE' THEN ROUND((30 - 10) * RANDOM_VALUE + 10, 2)
	END	AS INVESTIGATION_COST,
	CASE
		WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
		WHEN ML_RESULT = 'TRUE POSITIVE' THEN ROUND((15 - 3) * RANDOM_VALUE + 3, 2)
		WHEN ML_RESULT = 'FALSE POSITIVE' THEN ROUND((25 - 8) * RANDOM_VALUE + 8, 2)
		WHEN ML_RESULT = 'FALSE NEGATIVE' THEN ROUND((40 - 10) * RANDOM_VALUE + 10, 2)
	END	AS CUSTOMER_SUPPORT_COST,
	CASE
		WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
		WHEN ML_RESULT = 'TRUE POSITIVE' THEN ROUND((3 - 0) * RANDOM_VALUE + 0, 2)
		WHEN ML_RESULT = 'FALSE POSITIVE' THEN ROUND((4 - 0.5) * RANDOM_VALUE + 0.5, 2)
		WHEN ML_RESULT = 'FALSE NEGATIVE' THEN ROUND((15 - 3) * RANDOM_VALUE + 3, 2)
	END	AS LOST_INTERCHANGE
FROM
	CTE