WITH CTE AS
(
	SELECT
		GET_ML_RESULT(T.IS_FRAUD::BOOLEAN, FD.FLAGGED::BOOLEAN)	AS ML_RESULT,
		FC.*,
	FROM
		'project/UNCLEAN_DATASETS/fraud_costs.csv'				FC
		INNER JOIN 'project/CLEAN_DATASETS/TRANSACTIONS.csv'	T ON FC.TRANSACTION_ID = T.ID
		INNER JOIN 'project/CLEAN_DATASETS/FRAUD_DECISIONS.csv'	FD ON T.ID = FD.TRANSACTION_ID
)
SELECT
	CASE
		WHEN ML_RESULT = ''
	END												AS INVESTIGATION_COST
FROM
	CTE