SELECT
	ID																					AS ID,
	ACCOUNT_ID																			AS ACCOUNT_ID,
	DATE '1899-12-31' + CAST(FLOOR(TIMESTAMP) AS int) - 1								AS DATE,
	CAST(TIME '00:00:00' + INTERVAL (ROUND(TIMESTAMP % 1 * 86400)) SECOND AS varchar)	AS TIME,
	SPLIT_PART(AMOUNT, ' ', 1)															AS AMOUNT,
	SPLIT_PART(AMOUNT, ' ', 2)															AS CURRENCY,
	-- MISSING THE ACCOUNT_FEES PROCESSING
	CASE
		WHEN FD.FLAGGED = '1' THEN 0
		ELSE ACCOUNT_FEES
	END																					AS ACCOUNT_FEES,
	REPLACE(UPPER(MERCHANT_CATEGORY), '_', ' ')											AS MERCHANT_CATEGORY,
	CASE
		WHEN CHANNEL IN('web_payment', 'web-browser') THEN 'WEB'
		ELSE REPLACE(UPPER(CHANNEL), '_', ' ')
	END																					AS CHANNEL,
	UPPER(COUNTRY)																		AS COUNTRY,
	CASE
		WHEN IS_FRAUD IN('TRUE', 'Y') THEN '1'
		WHEN IS_FRAUD IN('FALSE', 'N') THEN '0'
		ELSE IS_FRAUD
	END																					AS IS_FRAUD
FROM
	'project/UNCLEAN_DATASETS/transactions.csv'	T
	INNER JOIN 'project/CLEAN_DATASETS/FRAUD_DECISIONS.csv'	FD ON T.ID = FD.TRANSACTION_ID