WITH UNPIVOTED_TEST_CASE_1 AS
(
	UNPIVOT
		(SELECT CAST(COLUMNS(*) AS varchar) FROM test_case_1_df)
	ON COLUMNS(*) INTO NAME KPI VALUE VALUE
),
UNPIVOTED_TEST_CASE_2 AS
(
	UNPIVOT
		(SELECT CAST(COLUMNS(*) AS varchar) FROM test_case_2_df)
	ON COLUMNS(*) INTO NAME KPI VALUE VALUE
)
SELECT
	UNPIVOTED_TEST_CASE_1.KPI						AS KPI,
	UNPIVOTED_TEST_CASE_1.VALUE						AS TEST_CASE_1,
	UNPIVOTED_TEST_CASE_2.VALUE						AS TEST_CASE_2,
	(CAST(UNPIVOTED_TEST_CASE_2.VALUE AS double) -
	CAST(UNPIVOTED_TEST_CASE_1.VALUE AS double)) /
	CAST(UNPIVOTED_TEST_CASE_1.VALUE AS double)		AS COMPARISON
FROM
	UNPIVOTED_TEST_CASE_1
	INNER JOIN UNPIVOTED_TEST_CASE_2 ON UNPIVOTED_TEST_CASE_1.KPI = UNPIVOTED_TEST_CASE_2.KPI
WHERE
	UNPIVOTED_TEST_CASE_1.KPI IN(
		'FALSE_POSITIVE_RATE',
		'GRAND_TOTAL',
		'FRAUD_DETECTION_RATE',
		'PRECISION',
		'ACCURACY',
		'TOTAL_USD_FEES',
		'TOTAL_FRAUD_LOSS',
		'TOTAL_INVESTIGATION_COST',
		'TOTAL_CUSTOMER_SUPPORT_COST',
		'TOTAL_LOST_INTERCHANGE'
	)