WITH COMBINED_FOREX_PAIRS_CTE AS
(
	SELECT
		DATE,
		FX_PAIR,
		LEFT(FX_PAIR, 3)	AS PRINCIPAL_CURRENCY,
		RIGHT(FX_PAIR, 3)	AS SECONDARY_CURRENCY,
		OPEN_PRICE
	FROM
		(
			UNPIVOT 'project/CLEAN_DATASETS/CLEAN_COMBINED_EXCHANGE_RATES.csv'
			ON COLUMNS(* EXCLUDE DATE) INTO NAME FX_PAIR VALUE OPEN_PRICE
		)
),
ACCOUNT_CHARGED_AMOUNT_CTE AS
(
	SELECT
		T.ID	AS TRANSACTION_ID,
		CASE
			WHEN A.CURRENCY = CURRENCY_PAIR_CTE.PRINCIPAL_CURRENCY THEN T.AMOUNT / CURRENCY_PAIR_CTE.OPEN_PRICE
			WHEN A.CURRENCY = CURRENCY_PAIR_CTE.SECONDARY_CURRENCY THEN T.AMOUNT * CURRENCY_PAIR_CTE.OPEN_PRICE
			ELSE T.AMOUNT
		END		AS ACCOUNT_CHARGED_AMOUNT
	FROM
		'project/CLEAN_DATASETS/TRANSACTIONS.csv'			T
		INNER JOIN 'project/CLEAN_DATASETS/ACCOUNTS.csv'	A ON T.ACCOUNT_ID = A.ID
		LEFT JOIN COMBINED_FOREX_PAIRS_CTE					CURRENCY_PAIR_CTE ON CURRENCY_PAIR_CTE.DATE = T.DATE AND
			(
				(CURRENCY_PAIR_CTE.PRINCIPAL_CURRENCY = A.CURRENCY AND CURRENCY_PAIR_CTE.SECONDARY_CURRENCY = T.CURRENCY)
				OR (CURRENCY_PAIR_CTE.PRINCIPAL_CURRENCY = T.CURRENCY AND CURRENCY_PAIR_CTE.SECONDARY_CURRENCY = A.CURRENCY)
			)
)
SELECT
	T.ID																		AS ID,
	T.ACCOUNT_ID																AS ACCOUNT_ID,
	T.DATE																		AS DATE,
	CAST(T.TIME AS varchar)														AS TIME,
	ACA_CTE.ACCOUNT_CHARGED_AMOUNT												AS ACCOUNT_CHARGED_AMOUNT,
	A.CURRENCY																	AS ACCOUNT_CURRENCY,
	CONCAT(USD_PAIR_CTE.PRINCIPAL_CURRENCY, USD_PAIR_CTE.SECONDARY_CURRENCY)	AS USD_PAIR,
	USD_PAIR_CTE.OPEN_PRICE														AS USD_RATE,
	T.MERCHANT_CATEGORY															AS MERCHANT_CATEGORY,
	T.CHANNEL																	AS CHANNEL,
	T.COUNTRY																	AS COUNTRY,
	TRV.RANDOM_VALUE															AS COST_VARIATION_FACTOR,
	FD.ML_SCORE																	AS ML_SCORE,
	T.IS_FRAUD																	AS IS_FRAUD
FROM
	'project/CLEAN_DATASETS/TRANSACTIONS.csv'					T
	INNER JOIN 'project/CLEAN_DATASETS/ACCOUNTS.csv'			A ON T.ACCOUNT_ID = A.ID
	INNER JOIN 'project/CLEAN_DATASETS/FRAUD_DECISIONS.csv'		FD ON T.ID = FD.TRANSACTION_ID
	LEFT JOIN ACCOUNT_CHARGED_AMOUNT_CTE						ACA_CTE ON T.ID = ACA_CTE.TRANSACTION_ID
	INNER JOIN 'project/ANALYSIS/TRANSACTION_RANDOM_VALUES.csv'	TRV ON T.ID = TRV.TRANSACTION_ID
	LEFT JOIN COMBINED_FOREX_PAIRS_CTE							USD_PAIR_CTE ON T.DATE = USD_PAIR_CTE.DATE AND
		(
			(USD_PAIR_CTE.PRINCIPAL_CURRENCY = A.CURRENCY AND USD_PAIR_CTE.SECONDARY_CURRENCY = 'USD')
			OR (USD_PAIR_CTE.PRINCIPAL_CURRENCY = 'USD' AND USD_PAIR_CTE.SECONDARY_CURRENCY = A.CURRENCY)
		)
