SET VARIABLE COMISSION_RATE = 0.0185;

WITH COMBINED_FOREX_PAIRS_CTE AS
(
	SELECT
		DATE,
		FX_PAIR,
		LEFT(FX_PAIR, 3)	AS PRINCIPAL_CURRENCY,
		RIGHT(FX_PAIR, 3)	AS SECONDARY_CURRENCY,
		OPEN_PRICE
	FROM
		(
			UNPIVOT 'project/CLEAN_DATASETS/CLEAN_COMBINED_EXCHANGE_RATES.csv'
			ON COLUMNS(* EXCLUDE DATE) INTO NAME FX_PAIR VALUE OPEN_PRICE
		)
),
AGG_FX_RATES_CTE AS
(
	SELECT
		T.ID			AS ID,
		T.DATE			AS DATE,
		T.ACCOUNT_FEES	AS ACCOUNT_FEES,
		A.CURRENCY		AS ACC_CURR,
		GET_ML_RESULT(T.IS_FRAUD::BOOLEAN, FD.FLAGGED::BOOLEAN)	AS ML_RESULT,
		CASE
			WHEN A.CURRENCY = CFP_CTE.PRINCIPAL_CURRENCY THEN T.AMOUNT / CFP_CTE.OPEN_PRICE
			WHEN A.CURRENCY = CFP_CTE.SECONDARY_CURRENCY THEN T.AMOUNT * CFP_CTE.OPEN_PRICE
			ELSE T.AMOUNT
		END				AS ACCOUNT_CHARGED_AMOUNT
	FROM
		'project/CLEAN_DATASETS/TRANSACTIONS.csv'				AS T
		LEFT JOIN 'project/CLEAN_DATASETS/FRAUD_DECISIONS.csv'	AS FD ON T.ID = FD.TRANSACTION_ID
		LEFT JOIN 'project/CLEAN_DATASETS/ACCOUNTS.csv'			AS A ON A.ID = T.ACCOUNT_ID
		LEFT JOIN COMBINED_FOREX_PAIRS_CTE						AS CFP_CTE ON CFP_CTE.DATE = T.DATE AND
		(
			(CFP_CTE.PRINCIPAL_CURRENCY = A.CURRENCY AND CFP_CTE.SECONDARY_CURRENCY = T.CURRENCY)
			OR (CFP_CTE.PRINCIPAL_CURRENCY = T.CURRENCY AND CFP_CTE.SECONDARY_CURRENCY = A.CURRENCY)
		)
),
CTE3 AS
(
	SELECT
		AFR_CTE.ACC_CURR,
		ACCOUNT_FEES,
		ACCOUNT_CHARGED_AMOUNT,


		CASE
			WHEN CFP_CTE.PRINCIPAL_CURRENCY = 'USD' THEN ACCOUNT_CHARGED_AMOUNT / CFP_CTE.OPEN_PRICE
			WHEN CFP_CTE.SECONDARY_CURRENCY = 'USD' THEN ACCOUNT_CHARGED_AMOUNT * CFP_CTE.OPEN_PRICE
			ELSE ACCOUNT_CHARGED_AMOUNT
		END																AS USD_AMOUNT,



		CASE
			WHEN CFP_CTE.PRINCIPAL_CURRENCY = 'USD' THEN ACCOUNT_CHARGED_AMOUNT / CFP_CTE.OPEN_PRICE * GETVARIABLE('COMISSION_RATE')
			WHEN CFP_CTE.SECONDARY_CURRENCY = 'USD' THEN ACCOUNT_CHARGED_AMOUNT * CFP_CTE.OPEN_PRICE * GETVARIABLE('COMISSION_RATE')
			ELSE ACCOUNT_CHARGED_AMOUNT * GETVARIABLE('COMISSION_RATE')
		END																AS USD_FEES,
		CASE
			WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
			WHEN ML_RESULT = 'TRUE POSITIVE' THEN -ROUND((20 - 5) * TRV.RANDOM_VALUE + 5, 2)
			WHEN ML_RESULT = 'FALSE POSITIVE' THEN -ROUND((12 - 2) * TRV.RANDOM_VALUE + 2, 2)
			WHEN ML_RESULT = 'FALSE NEGATIVE' THEN -ROUND((30 - 10) * TRV.RANDOM_VALUE + 10, 2)
		END	AS INVESTIGATION_COST,
		CASE
			WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
			WHEN ML_RESULT = 'TRUE POSITIVE' THEN -ROUND((15 - 3) * TRV.RANDOM_VALUE + 3, 2)
			WHEN ML_RESULT = 'FALSE POSITIVE' THEN -ROUND((25 - 8) * TRV.RANDOM_VALUE + 8, 2)
			WHEN ML_RESULT = 'FALSE NEGATIVE' THEN -ROUND((40 - 10) * TRV.RANDOM_VALUE + 10, 2)
		END	AS CUSTOMER_SUPPORT_COST,
		CASE
			WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
			WHEN ML_RESULT = 'TRUE POSITIVE' THEN -ROUND((3 - 0) * TRV.RANDOM_VALUE + 0, 2)
			WHEN ML_RESULT = 'FALSE POSITIVE' THEN -ROUND((4 - 0.5) * TRV.RANDOM_VALUE + 0.5, 2)
			WHEN ML_RESULT = 'FALSE NEGATIVE' THEN -ROUND((15 - 3) * TRV.RANDOM_VALUE + 3, 2)
		END	AS LOST_INTERCHANGE
	FROM
		AGG_FX_RATES_CTE									AS AFR_CTE
		INNER JOIN 'project/TRANSACTION_RANDOM_VALUES.csv'	AS TRV ON AFR_CTE.ID = TRV.TRANSACTION_ID
		LEFT JOIN COMBINED_FOREX_PAIRS_CTE					AS CFP_CTE ON CFP_CTE.DATE = AFR_CTE.DATE AND
		(
			(CFP_CTE.PRINCIPAL_CURRENCY = AFR_CTE.ACC_CURR AND CFP_CTE.SECONDARY_CURRENCY = 'USD')
			OR (CFP_CTE.PRINCIPAL_CURRENCY = 'USD' AND CFP_CTE.SECONDARY_CURRENCY = AFR_CTE.ACC_CURR)
		)
)
SELECT
	ACC_CURR,
	ACCOUNT_CHARGED_AMOUNT,
	ACCOUNT_FEES,
	USD_AMOUNT,
	USD_FEES														AS USD_FEES
	--SUM(INVESTIGATION_COST + CUSTOMER_SUPPORT_COST + LOST_INTERCHANGE)	AS TOTAL_COSTS
FROM
	CTE3