WITH CTE AS
(
	SELECT
		ML_RESULT,
		COUNT(*)	AS COUNT
	FROM
		test_case_transactions_df
	GROUP BY
		ML_RESULT
),
CTE2 AS
(
	SELECT
		MAX(CASE WHEN ML_RESULT = 'FALSE POSITIVE' THEN COUNT ELSE 0 END)	AS 'FALSE_POSITIVE',
		MAX(CASE WHEN ML_RESULT = 'FALSE NEGATIVE' THEN COUNT ELSE 0 END)	AS 'FALSE_NEGATIVE',
		MAX(CASE WHEN ML_RESULT = 'TRUE POSITIVE' THEN COUNT ELSE 0 END)	AS 'TRUE_POSITIVE',
		MAX(CASE WHEN ML_RESULT = 'TRUE NEGATIVE' THEN COUNT ELSE 0 END)	AS 'TRUE_NEGATIVE'
	FROM
		CTE
),
CTE3 AS
(
	SELECT
		SUM(USD_FEES)				AS TOTAL_USD_FEES,
		SUM(FRAUD_LOSS)				AS TOTAL_FRAUD_LOSS,
		SUM(INVESTIGATION_COST)		AS TOTAL_INVESTIGATION_COST,
		SUM(CUSTOMER_SUPPORT_COST)	AS TOTAL_CUSTOMER_SUPPORT_COST,
		SUM(LOST_INTERCHANGE)		AS TOTAL_LOST_INTERCHANGE,
		SUM(TOTAL_COSTS)			AS TOTAL_COSTS,
		SUM(GRAND_TOTAL)			AS GRAND_TOTAL
	FROM
		test_case_transactions_df
)
SELECT
	UUID()																								AS FRAUD_ANALYSIS_ID,
	TRUE_POSITIVE / (TRUE_POSITIVE + FALSE_NEGATIVE)													AS FRAUD_DETECTION_RATE,
	FALSE_POSITIVE / (FALSE_POSITIVE + TRUE_NEGATIVE)													AS FALSE_POSITIVE_RATE,
	TRUE_POSITIVE / (TRUE_POSITIVE + FALSE_POSITIVE)													AS PRECISION,
	(TRUE_POSITIVE + TRUE_NEGATIVE) / (TRUE_POSITIVE + TRUE_NEGATIVE + FALSE_POSITIVE + FALSE_NEGATIVE)	AS ACCURACY,
	TOTAL_USD_FEES																						AS TOTAL_USD_FEES,
	TOTAL_FRAUD_LOSS																					AS TOTAL_FRAUD_LOSS,
	TOTAL_INVESTIGATION_COST																			AS TOTAL_INVESTIGATION_COST,
	TOTAL_CUSTOMER_SUPPORT_COST																			AS TOTAL_CUSTOMER_SUPPORT_COST,
	TOTAL_LOST_INTERCHANGE																				AS TOTAL_LOST_INTERCHANGE,
	TOTAL_COSTS																							AS TOTAL_COSTS,
	GRAND_TOTAL																							AS GRAND_TOTAL
FROM
	CTE3, CTE2