WITH CTE AS
(
	SELECT
		ID,
		GET_ML_RESULT(IS_FRAUD::BOOLEAN, FLAGGED::BOOLEAN)	AS ML_RESULT
	FROM
		joined_tables_for_analysis
),
CTE2 AS
(
	SELECT
		ML_RESULT,
		COUNT(*)	AS COUNT
	FROM
		CTE
	GROUP BY
		ML_RESULT
),
CTE3 AS
(
	SELECT
		MAX(CASE WHEN ML_RESULT = 'FALSE POSITIVE' THEN COUNT ELSE 0 END)	AS 'FALSE_POSITIVE',
		MAX(CASE WHEN ML_RESULT = 'FALSE NEGATIVE' THEN COUNT ELSE 0 END)	AS 'FALSE_NEGATIVE',
		MAX(CASE WHEN ML_RESULT = 'TRUE POSITIVE' THEN COUNT ELSE 0 END)	AS 'TRUE_POSITIVE',
		MAX(CASE WHEN ML_RESULT = 'TRUE NEGATIVE' THEN COUNT ELSE 0 END)	AS 'TRUE_NEGATIVE'
	FROM
		CTE2
),
CTE4 AS
(
	SELECT
		SUM(CASE WHEN FLAGGED = 1 THEN 0 ELSE UNPROCESSED_USD_FEES END)	AS USD_FEES
	FROM
		joined_tables_for_analysis
),
CTE5 AS
(
	SELECT
		SUM(CASE
			WHEN ML_RESULT = 'FALSE NEGATIVE' THEN -JTA.TRANSACTION_USD_AMOUNT
			ELSE 0
		END)	AS TOTAL_FRAUD_LOSS,
		SUM(CASE
			WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
			WHEN ML_RESULT = 'TRUE POSITIVE' THEN -ROUND((20 - 5) * JTA.COST_VARIATION_FACTOR + 5, 2)
			WHEN ML_RESULT = 'FALSE POSITIVE' THEN -ROUND((12 - 2) * JTA.COST_VARIATION_FACTOR + 2, 2)
			WHEN ML_RESULT = 'FALSE NEGATIVE' THEN -ROUND((30 - 10) * JTA.COST_VARIATION_FACTOR + 10, 2)
		END)	AS TOTAL_INVESTIGATION_COST,
		SUM(CASE
			WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
			WHEN ML_RESULT = 'TRUE POSITIVE' THEN -ROUND((15 - 3) * JTA.COST_VARIATION_FACTOR + 3, 2)
			WHEN ML_RESULT = 'FALSE POSITIVE' THEN -ROUND((25 - 8) * JTA.COST_VARIATION_FACTOR + 8, 2)
			WHEN ML_RESULT = 'FALSE NEGATIVE' THEN -ROUND((40 - 10) * JTA.COST_VARIATION_FACTOR + 10, 2)
		END)	AS TOTAL_CUSTOMER_SUPPORT_COST,
		SUM(CASE
			WHEN ML_RESULT = 'TRUE NEGATIVE' THEN 0
			WHEN ML_RESULT = 'TRUE POSITIVE' THEN -ROUND((3 - 0) * JTA.COST_VARIATION_FACTOR + 0, 2)
			WHEN ML_RESULT = 'FALSE POSITIVE' THEN -ROUND((4 - 0.5) * JTA.COST_VARIATION_FACTOR + 0.5, 2)
			WHEN ML_RESULT = 'FALSE NEGATIVE' THEN -ROUND((15 - 3) * JTA.COST_VARIATION_FACTOR + 3, 2)
		END)	AS TOTAL_LOST_INTERCHANGE
	FROM
		CTE
		INNER JOIN joined_tables_for_analysis	JTA ON CTE.ID = JTA.ID
)
SELECT
	UUID()																											AS FRAUD_ANALYSIS_ID,
	TRUE_POSITIVE / (TRUE_POSITIVE + FALSE_NEGATIVE)																AS FRAUD_DETECTION_RATE,
	FALSE_POSITIVE / (FALSE_POSITIVE + TRUE_NEGATIVE)																AS FALSE_POSITIVE_RATE,
	TRUE_POSITIVE / (TRUE_POSITIVE + FALSE_POSITIVE)																AS PRECISION,
	(TRUE_POSITIVE + TRUE_NEGATIVE) / (TRUE_POSITIVE + TRUE_NEGATIVE + FALSE_POSITIVE + FALSE_NEGATIVE)				AS ACCURACY,
	USD_FEES																										AS USD_FEES,
	TOTAL_FRAUD_LOSS																								AS TOTAL_FRAUD_LOSS,
	TOTAL_INVESTIGATION_COST																						AS TOTAL_INVESTIGATION_COST,
	TOTAL_CUSTOMER_SUPPORT_COST																						AS TOTAL_CUSTOMER_SUPPORT_COST,
	TOTAL_LOST_INTERCHANGE																							AS TOTAL_LOST_INTERCHANGE,
	USD_FEES + TOTAL_FRAUD_LOSS + TOTAL_INVESTIGATION_COST + TOTAL_CUSTOMER_SUPPORT_COST + TOTAL_LOST_INTERCHANGE	AS GRAND_TOTAL,
FROM
	CTE3, CTE4, CTE5