SELECT
	DT.ID						AS ID,
	DT.DATE						AS DATE,
	CAST(DT.TIME AS varchar)	AS TIME,
	DT.TRANSACTION_USD_AMOUNT	AS TRANSACTION_USD_AMOUNT,
	DT.UNPROCESSED_USD_FEES		AS UNPROCESSED_USD_FEES,
	DT.MERCHANT_CATEGORY		AS MERCHANT_CATEGORY,
	DT.CHANNEL					AS CHANNEL,
	DT.COUNTRY					AS TRANSACTION_COUNTRY,
	DT.COST_VARIATION_FACTOR	AS COST_VARIATION_FACTOR,
	DT.ML_SCORE					AS ML_SCORE,
	DT.ML_SCORE / 1000			AS ML_PROBABILITY,
	DT.IS_FRAUD					AS IS_FRAUD,
	A.TYPE						AS TYPE,
	A.CURRENCY					AS ACCOUNT_CURRENCY,
	A.BALANCE					AS BALANCE,
	A.OPEN_DATE					AS OPEN_DATE,
	A.STATUS					AS STATUS,
	C.FULL_NAME					AS FULL_NAME,
	C.AGE						AS AGE,
	C.GENDER					AS GENDER,
	C.COUNTRY					AS CUSTOMER_COUNTRY,
	C.CREDIT_LIMIT				AS CREDIT_LIMIT,
	C.CUSTOMER_LIFETIME_VALUE	AS CUSTOMER_LIFETIME_VALUE,
	FD.FLAGGED					AS FLAGGED
FROM
	'project/ANALYSIS/DENORMALIZED_TRANSACTIONS.csv'		DT
	INNER JOIN 'project/CLEAN_DATASETS/ACCOUNTS.csv'		A ON DT.ACCOUNT_ID = A.ID
	INNER JOIN 'project/CLEAN_DATASETS/CUSTOMERS.csv'		C ON A.CUSTOMER_ID = C.ID
	INNER JOIN 'project/CLEAN_DATASETS/FRAUD_DECISIONS.csv'	FD ON DT.ID = FD.TRANSACTION_ID